spring:
  datasource:
    url: jdbc:mysql:///hls_train?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

fcant:
  tel: 17826260016
  exist: True
  properties: YHU
  check:
    code: 123456
management:
  endpoints:
    web:
      exposure:
        include: '*'
